### ISSUE TITLE
maybe can provide Model.get() function for get obj by id？

### ISSUE THREAD

**Issue by ischaojie** [aminalaee/mongox#35]
Although we can use `Model.query({"_id": id}).first()` to get object by id，But maybe it's better to use a shotcut function like:

```
Model.get("id")
```

**Comment by aminalaee** [comment]
Hmmm..this is interesting. Django does this too.

Yeah I think we should add it. PRs are welcome.

**Comment by ischaojie** [comment]
Just a proposal🐯, maybe should be defined by developer.

**Comment by aminalaee** [comment]
I think this is a nice feature, I just can't find a way to add it to our APIs.

So we normally have:

```python
Model.query(Model.name == "A").get()
```
Where get doesn't really accept any arguments.

I think the closest thing to that idea for me would be:

```python
Model.get_by_id()
```

Otherwise we need to modify our API to be something like:

```python
Model.get()
Model.all()
```
And remove the `.query()` which I think has some pros and cons.

Any feedback would be appreciated.

**Comment by aminalaee** [comment]
PRs are always welcome :)
